### ISSUE TITLE
Kompatibilität mit FontAwesome 5 (Pro)

### ISSUE THREAD

**Issue by jankout** [madeyourday/contao-rocksolid-icon-picker#10]
Hallo, 

es wäre schön, wenn es auch mit FontAwesome 5 (Pro) funktionieren könnte. Danke. 

Liebe Grüße,

Jan

**Comment by ausi** [comment]
Der Picker sollte mit jedem Icon-Font funktionieren.  
Was genau funktioniert mit FontAwesome nicht?

**Comment by jankout** [comment]
Die Suche. Wenn man nach Facebook sucht, kommt nicht. Ich denke, dass sie die Namen geändert haben.

**Comment by ausi** [comment]
> Ich denke, dass sie die Namen geändert haben.

In was wurde der Name geändert?  
Wenn das Icon nicht mehr „Facebook“ heißt, kann es der Icon-Picker auch nicht finden.

**Comment by jankout** [comment]
Das weiß ich leider nicht. Das ist meine Vermutung. Die 5. Version ist grundlegend anders.

**Comment by ausi** [comment]
Ich konnte den Fehler mit FontAwesome 5.0.9 nicht reproduzieren.

Hier ein Screenshot der alle vier Facebook-Icons anzeigt:
![icon-picker-fontawesome-5](https://user-images.githubusercontent.com/367169/38029318-d404ae26-3295-11e8-9b38-c009e3c72eb4.png)

**Comment by jankout** [comment]
Ok. Danke. Welche Datei soll ich als Basis nehmen - ich benutze die Pro-Version? Muss ich vorher Cache leeren, wenn ich von der 4. zur 5. Version wechsele?

**Comment by jankout** [comment]
Danke.

**Comment by jankout** [comment]
Es tut mir leid, aber ich kann das immer noch nicht hinbekommen. Ich habe das Cache gelöscht - von Contao und Browser. Woran kann es noch liegen? Ich benutze **FontAwesome Pro 5.2**, und zwar **fa-solid-900.svg**. 
![fontawesome 5 pro](https://user-images.githubusercontent.com/3715050/43315083-2fd9866e-9195-11e8-8c5c-69c887f07382.gif)

**Comment by jankout** [comment]
Ok, ich habe es herausgefunden. Die Firmenlogos liegen nämlich in einer separaten Datei - fa-brands-400.svg. Diese muss man nutzen.
