### ISSUE TITLE
FR: Add multiple icons

### ISSUE THREAD

**Issue by neckarpixel** [madeyourday/contao-rocksolid-icon-picker#13]
It would be great to add a functionality to add multiple icons, so that you will receive an array in template, may be like this
`foreach($this->icons as $icon) { ?>
<i>&#x<?= $icon['name']; ?></i>
<?php
}`

**Comment by ausi** [comment]
If you use the Custom Elements extension you can achieve that by using the input type `list`: <https://rocksolidthemes.com/de/contao/plugins/custom-content-elements/dokumentation#feldtyp-list>
