### ISSUE TITLE
Composer Error after Update

### ISSUE THREAD

**Issue by cboelter** [madeyourday/contao-rocksolid-icon-picker#4]
I'm using Contao 3.4.5 after composer update I get the following errors ...

```
SplFileInfo::isDir(): open_basedir restriction in effect. File(/composer/vendor/madeyourday/contao-rocksolid-icon-picker/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resou
```

**Comment by ausi** [comment]
Please check if this version fixes the issue: `"madeyourday/contao-rocksolid-icon-picker": "dev-master as 1.0.x-dev"`

**Comment by christianromeni** [comment]
Ich glaub ich habe ein ähnliches Problem mit dem Icon Picker:
The first argument to copy() function cannot be a directory in composer/vendor/contao-community-alliance/composer-plugin/src/ContaoCommunityAlliance/Composer/Plugin/CopyInstaller.php 

Ein Update geht leider nicht, weil:
madeyourday/contao-rocksolid-custom-elements v1.2.9 requires madeyourday/contao-rocksolid-icon-picker ~1.0 -> no matching package found.

**Comment by ausi** [comment]
Using the version `dev-master as 1.0.x-dev` should solve the “no matching package found” error.

**Comment by christianromeni** [comment]
I have to enter this in Expert Mode right?
Then it did not seem to work.

I noticed when using syncCto:
SplFileInfo::getSize(): stat failed for /home/php-deploy/sites/dev/exco.dev.brainplanner.de/composer/vendor/madeyourday/contao-rocksolid-columns/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao/src/MadeYourDay/Contao/Resources/contao

**Comment by christianromeni** [comment]
Das scheint doch funktioniert zu haben, selbes allerdings bei contao-rocksolid-columns

**Comment by ausi** [comment]
It’s likely that all RockSolid extensions have this issue. If @cboelter confirms that the fix solved his issue, I will fix it in the other extensions as well.

**Comment by cboelter** [comment]
Same issue as before :(

**Comment by ausi** [comment]
@cboelter Can you post the new error message please?

**Comment by christianromeni** [comment]
@cboelter I had to completely remove the module and add it again afterwards.. Then the message changed to another rocksolid extension.

**Comment by cboelter** [comment]
This is the message I get now ... It is a Contao 3.2.X Contao but I think it doesn't matter.
```

Warning: copy(): The first argument to copy() function cannot be a directory in composer/vendor/contao-community-alliance/composer-plugin/src/ContaoCommunityAlliance/Composer/Plugin/CopyInstaller.php on line 141

#0 [internal function]: __error(2, 'copy(): The fir...', '/Applications/M...', 141, Array)
#1 composer/vendor/contao-community-alliance/composer-plugin/src/ContaoCommunityAlliance/Composer/Plugin/CopyInstaller.php(141): copy('/Applications/M...', '/Applications/M...')
#2 composer/vendor/contao-community-alliance/composer-plugin/src/ContaoCommunityAlliance/Composer/Plugin/CopyInstaller.php(43): ContaoCommunityAlliance\Composer\Plugin\CopyInstaller->updateAllCopies(Array, '/Applications/M...', '/Applications/M...', 13)
#3 composer/vendor/contao-community-alliance/composer-plugin/src/ContaoCommunityAlliance/Composer/Plugin/AbstractInstaller.php(137): ContaoCommunityAlliance\Composer\Plugin\CopyInstaller->updateSources(Array, Object(Composer\Package\CompletePackage))
#4 phar://composer/composer.phar/src/Composer/Installer/LibraryInstaller.php(87): ContaoCommunityAlliance\Composer\Plugin\AbstractInstaller->installCode(Object(Composer\Package\CompletePackage))
#5 phar://composer/composer.phar/src/Composer/Installer/InstallationManager.php(152): Composer\Installer\LibraryInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#6 phar://composer/composer.phar/src/Composer/Installer/InstallationManager.php(139): Composer\Installer\InstallationManager->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\DependencyResolver\Operation\InstallOperation))
#7 phar://composer/composer.phar/src/Composer/Installer.php(580): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\DependencyResolver\Operation\InstallOperation))
#8 phar://composer/composer.phar/src/Composer/Installer.php(230): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array, false)
#9 system/modules/!composer/src/Controller/UpdatePackagesController.php(151): Composer\Installer->run()
#10 system/modules/!composer/src/Controller/UpdatePackagesController.php(55): ContaoCommunityAlliance\Contao\Composer\Controller\UpdatePackagesController->runInline(Array, false)
#11 system/modules/!composer/src/ClientBackend.php(218): ContaoCommunityAlliance\Contao\Composer\Controller\UpdatePackagesController->handle(Object(Contao\Input))
#12 system/modules/core/classes/Backend.php(271): ContaoCommunityAlliance\Contao\Composer\ClientBackend->generate()
#13 contao/main.php(142): Contao\Backend->getBackendModule('composer')
#14 contao/main.php(293): Main->run()
#15 {main}

```

**Comment by cboelter** [comment]
The same error occurs on a clean Contao 3.5.

**Comment by ausi** [comment]
This warning message looks like its not able to copy the symlink, but the installation should have been successful.

Is the extension listed as “installed” in the Composer client?
And does the extension work correctly?

**Comment by christianromeni** [comment]
I have now checked in another contao installation, I got the same error after updateing to 3.5
After updating to the latest dev-master, the problem seems fixed.
Seems like what you changed will be fixing the other modules as well. Would be awesome if you could fix in time.

Thank you.

**Comment by ausi** [comment]
This bug is now fixed in all extensions. With the pull request contao-community-alliance/composer-plugin#43 the issue should be fixed completely.

**Comment by christianromeni** [comment]
Nice! Thank you very much.

**Comment by fritzmg** [comment]
Hm, version 1.0.8 of contao-rocksolid-icon-picker still causes
```
  - Removing madeyourday/contao-rocksolid-icon-picker (v1.0.6)
  - Installing madeyourday/contao-rocksolid-icon-picker (v1.0.8)
    Loading from cache



                                                                       
  [ErrorException]                                                     
  copy(): The first argument to copy() function cannot be a directory  
```
for me at least

**Comment by ausi** [comment]
The error `SplFileInfo::isDir(): open_basedir restriction in effect.` is fixed in all extensions. The error `copy(): The first argument to copy() function cannot be a directory` has to be fixed in the [composer-plugin](https://github.com/contao-community-alliance/composer-plugin), see contao-community-alliance/composer-plugin#43.

**Comment by fritzmg** [comment]
I see, thank you :)
