### ISSUE TITLE
Contao 4.2 Theme Compatibility

### ISSUE THREAD

**Issue by christianromeni** [madeyourday/contao-rocksolid-icon-picker#5]
The Icon Picker is noch compatible with the new Contao 4.2 theme. The search bar is too high:

![image](https://cloud.githubusercontent.com/assets/1358040/16821728/2d2a00f6-4958-11e6-984d-2c9c535a06be.png)

**Comment by asifeqbal** [comment]
Ich installierte rocksolid-Icon-Picker-Erweiterung aber nach der Installation, wie kann ich es verwenden. Weil nach der Installation kann ich nicht gesehen es auf meinem contao Projekt bitte vorschlagen me.Thanks

**Comment by ausi** [comment]
Fixed in bb00e6c1fdde14181d649871382ffec102fd9a5a
