### ISSUE TITLE
Search fields with FontAwesome: support for all icons

### ISSUE THREAD

**Issue by jankout** [madeyourday/contao-rocksolid-icon-picker#8]
Now it is not possible to search for all icons included in the FontAwesome. Please, add support for all icons in the CSS, SVG file of FontAwesome. Thank you.

**Comment by ausi** [comment]
I was not able to reproduce this issue.

The SVG font of FontAwesome [includes `glyph-name` attributes](https://github.com/FortAwesome/Font-Awesome/blob/c53b03d9a1d86365fb1f5b4b450205e7d9824442/fonts/fontawesome-webfont.svg?short_path=855c845#L52) which are used by the icon picker.

**Comment by jankout** [comment]
Unfortunately, not all glyphs have a name like in the CSS file. E.x. paypal. When I tip "paypal" your extension cannot find it. Wouldn't it be better to use the CSS as reference file?

**Comment by jankout** [comment]
Or should I contact the devolepers of FontAwesome to ask them to improve it?

**Comment by ausi** [comment]
I think both issues should get fixed. The icon picker should combine all names it can find (from SVG, CSS and HTML) and FontAwesome should use the same icon names in the SVG file as in the CSS file.

**Comment by jankout** [comment]
I've left a message in the repository of the new FW5.
